#!/usr/bin/env python3
"""Generate firmware/main/test_sequence.c and .h from a JSON sequence.

Usage (from the firmware/ directory):
    python scripts/generate_sequence.py [path/to/sequence.json]

The default input file is sequences/demo.json.
"""

import argparse
import json
import sys
from pathlib import Path

OSCILLATOR_COUNT = 5

WAVEFORM_MAP = {
    "sine": "OSCILLATOR_WAVEFORM_SINE",
    "square": "OSCILLATOR_WAVEFORM_SQUARE",
    "triangle": "OSCILLATOR_WAVEFORM_TRIANGLE",
    "custom": "OSCILLATOR_WAVEFORM_CUSTOM",
}

LFO_WAVEFORM_MAP = {
    "sine": "MODULATOR_LFO_WAVEFORM_SINE",
    "square": "MODULATOR_LFO_WAVEFORM_SQUARE",
}

MODE_MAP = {
    "static": "MODULATOR_MODE_STATIC",
    "linear": "MODULATOR_MODE_LINEAR",
    "lfo": "MODULATOR_MODE_LFO",
}


def emit_static_modulator(mod: dict, target: str, lines: list[str]) -> None:
    lines.append(
        f"      steps[step].oscillators[osc].{target}.mode = {MODE_MAP['static']};"
    )
    lines.append(
        f"      steps[step].oscillators[osc].{target}.static_config.value = "
        f"{float(mod['value'])}f;"
    )


def emit_linear_modulator(mod: dict, target: str, lines: list[str]) -> None:
    lines.append(
        f"      steps[step].oscillators[osc].{target}.mode = {MODE_MAP['linear']};"
    )
    lines.append(
        f"      steps[step].oscillators[osc].{target}.linear_config.start_value = "
        f"{float(mod['start'])}f;"
    )
    lines.append(
        f"      steps[step].oscillators[osc].{target}.linear_config.end_value = "
        f"{float(mod['end'])}f;"
    )
    lines.append(
        f"      steps[step].oscillators[osc].{target}.linear_config.duration_ms = "
        f"{int(mod['duration_ms'])}U;"
    )


def emit_lfo_modulator(mod: dict, target: str, lines: list[str]) -> None:
    lines.append(
        f"      steps[step].oscillators[osc].{target}.mode = {MODE_MAP['lfo']};"
    )
    waveform = LFO_WAVEFORM_MAP[mod["waveform"]]
    lines.append(
        f"      steps[step].oscillators[osc].{target}.lfo_config.waveform = {waveform};"
    )
    lines.append(
        f"      steps[step].oscillators[osc].{target}.lfo_config.frequency_hz = "
        f"{float(mod['frequency_hz'])}f;"
    )
    lines.append(
        f"      steps[step].oscillators[osc].{target}.lfo_config.low = "
        f"{float(mod['low'])}f;"
    )
    lines.append(
        f"      steps[step].oscillators[osc].{target}.lfo_config.high = "
        f"{float(mod['high'])}f;"
    )


MODULATOR_DISPATCH = {
    "static": emit_static_modulator,
    "linear": emit_linear_modulator,
    "lfo": emit_lfo_modulator,
}


def generate_c(source_name: str, data: dict) -> str:
    lines: list[str] = [
        f"/* Auto-generated by generate_sequence.py from {source_name}. */",
        '#include "test_sequence.h"',
        "",
        '#include "modulator.h"',
        '#include "oscillator.h"',
        '#include "sequence.h"',
        "",
        "#include <stdint.h>",
        "#include <string.h>",
        "",
        "void build_demo_sequence(sequence_step_t *steps) {",
        "  (void)steps;",
        "",
    ]

    lines.append(
        "  memset(steps, 0, sizeof(sequence_step_t) * SEQUENCE_DEMO_STEP_COUNT);"
    )
    lines.append("")

    steps = data["steps"]
    for step_index, step in enumerate(steps):
        oscillators = step["oscillators"]
        if len(oscillators) != OSCILLATOR_COUNT:
            raise ValueError(
                f"Step {step_index}: expected {OSCILLATOR_COUNT} oscillators, "
                f"got {len(oscillators)}"
            )

        lines.append(f"  /* Step {step_index} */")
        lines.append("  {")
        lines.append(f"    const uint32_t step = {step_index}U;")
        lines.append(f"    steps[step].duration_ms = {int(step['duration_ms'])}U;")

        for osc_index, osc in enumerate(oscillators):
            waveform = WAVEFORM_MAP[osc.get("waveform", "sine")]
            phase_degrees = float(osc.get("phase_degrees", 0.0))
            frequency = osc["frequency"]
            brightness = osc["brightness"]
            duty = osc.get("duty", {"mode": "static", "value": 0.5})

            lines.append("    {")
            lines.append(f"      const uint8_t osc = {osc_index}U;")

            lines.append(
                f"      steps[step].oscillators[osc].static_config.waveform = {waveform};"
            )
            lines.append(
                f"      steps[step].oscillators[osc].static_config.phase_degrees = "
                f"{phase_degrees}f;"
            )
            lines.append(
                "      steps[step].oscillators[osc].static_config.custom_lut = NULL;"
            )

            for target, mod in (
                ("frequency", frequency),
                ("brightness", brightness),
                ("duty", duty),
            ):
                mode = mod["mode"]
                if mode not in MODULATOR_DISPATCH:
                    raise ValueError(
                        f"Step {step_index}, oscillator {osc_index}: "
                        f"unknown modulator mode '{mode}'"
                    )
                if mode == "linear" and "duration_ms" not in mod:
                    mod["duration_ms"] = step["duration_ms"]
                MODULATOR_DISPATCH[mode](mod, f"{target}_modulator", lines)

            lines.append("    }")

        lines.append("  }")

    lines.append("}")
    return "\n".join(lines) + "\n"


def generate_h(source_name: str, step_count: int) -> str:
    guard = "TEST_SEQUENCE_H"
    return f"""/* Auto-generated by generate_sequence.py from {source_name}. */
#ifndef {guard}
#define {guard}

#include "sequence.h"

#ifdef __cplusplus
extern "C" {{
#endif

/** @brief Number of steps in the generated demo sequence. */
#define SEQUENCE_DEMO_STEP_COUNT {step_count}U

/** @brief Populate the provided array with the demo sequence steps. */
void build_demo_sequence(sequence_step_t *steps);

#ifdef __cplusplus
}}
#endif

#endif /* {guard} */
"""


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate test_sequence.c/h from a JSON sequence."
    )
    parser.add_argument(
        "input",
        nargs="?",
        default="sequences/demo.json",
        help="JSON input file (default: sequences/demo.json)",
    )
    args = parser.parse_args()

    firmware_dir = Path(__file__).resolve().parent.parent
    input_path = firmware_dir / args.input
    if not input_path.is_file():
        print(f"Error: input file not found: {input_path}", file=sys.stderr)
        return 1

    with open(input_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    try:
        c_source = generate_c(input_path.name, data)
        h_source = generate_h(input_path.name, len(data["steps"]))
    except (KeyError, ValueError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    main_dir = firmware_dir / "main"
    main_dir.mkdir(parents=True, exist_ok=True)

    c_path = main_dir / "test_sequence.c"
    h_path = main_dir / "test_sequence.h"

    with open(c_path, "w", encoding="utf-8") as f:
        f.write(c_source)
    with open(h_path, "w", encoding="utf-8") as f:
        f.write(h_source)

    print(f"Generated {c_path}")
    print(f"Generated {h_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
