/* Auto-generated by generate_sequence.py from demo.json. */
#ifndef TEST_SEQUENCE_H
#define TEST_SEQUENCE_H

#include "sequence.h"

#ifdef __cplusplus
extern "C" {
#endif

/** @brief Number of steps in the generated demo sequence. */
#define SEQUENCE_DEMO_STEP_COUNT 1U

/** @brief Populate the provided array with the demo sequence steps. */
void build_demo_sequence(sequence_step_t *steps);

#ifdef __cplusplus
}
#endif

#endif /* TEST_SEQUENCE_H */
