/**
 * @file sequence.h
 * @brief Realtime parameter ownership for HypnoLight oscillators.
 *
 * This initial sequence component implements the realtime mode only. It owns
 * current static settings, frequencies, and brightness values for the five
 * oscillators, while oscillator generates waveforms and led_control drives PWM.
 */
#pragma once

#include <stdint.h>

#include "esp_err.h"
#include "oscillator.h"

/** @brief Operating modes supported by the future sequence engine. */
typedef enum {
  SEQUENCE_MODE_REALTIME,
  SEQUENCE_MODE_SEQUENCE,
} sequence_mode_t;

/** @brief Fixed evaluation interval for realtime parameter controls. */
#define SEQUENCE_TICK_PERIOD_MS 10U

/** @brief Supported realtime parameter control modes. */
typedef enum {
  SEQUENCE_PARAMETER_CONTROL_CONSTANT,
  SEQUENCE_PARAMETER_CONTROL_LINEAR,
} sequence_parameter_control_mode_t;

/**
 * @brief Current realtime parameters owned for one oscillator.
 *
 * The custom_lut pointer is retained only as configuration metadata. The
 * oscillator component copies custom waveform samples into its internal LUT.
 */
typedef struct {
  oscillator_static_config_t static_config;
  float frequency_hz;
  float brightness;
  sequence_parameter_control_mode_t frequency_mode;
  sequence_parameter_control_mode_t brightness_mode;
} sequence_realtime_oscillator_t;

/**
 * @brief Initialize realtime parameter state and all oscillator generators.
 *
 * All brightness and frequency values start at zero. The initial mode is
 * SEQUENCE_MODE_REALTIME.
 *
 * @return ESP_OK on success; otherwise, an error returned by oscillator_init().
 */
esp_err_t sequence_init(void);

/**
 * @brief Return the current operating mode.
 *
 * The initial implementation always returns SEQUENCE_MODE_REALTIME. Sequence
 * playback mode will be added with step loading and timing support.
 *
 * @return Current sequence operating mode.
 */
sequence_mode_t sequence_get_mode(void);

/**
 * @brief Apply static waveform configuration in realtime mode.
 *
 * The selected oscillator rebuilds its LUT and resets its phase according to
 * config->phase_degrees. Other oscillator state remains unchanged.
 *
 * @param[in] oscillator_id Oscillator ID in the range 0 to 4.
 * @param[in] config Static waveform configuration.
 *
 * @return ESP_OK on success or an error returned by oscillator_set_static().
 */
esp_err_t
sequence_realtime_set_static(uint8_t oscillator_id,
                             const oscillator_static_config_t *config);

/**
 * @brief Set one oscillator's realtime frequency.
 *
 * Updating frequency preserves the current DDS phase and does not rebuild the
 * waveform LUT.
 *
 * @param[in] oscillator_id Oscillator ID in the range 0 to 4.
 * @param[in] frequency_hz Frequency in the range accepted by oscillator.
 *
 * @return ESP_OK on success or an error returned by oscillator_set_frequency().
 */
esp_err_t sequence_realtime_set_frequency(uint8_t oscillator_id,
                                          float frequency_hz);

/**
 * @brief Set one oscillator's realtime brightness.
 *
 * Brightness is stored as a normalized factor and is consumed by the 1 kHz
 * output callback with the waveform value generated by oscillator.
 *
 * @param[in] oscillator_id Oscillator ID in the range 0 to 4.
 * @param[in] brightness Normalized brightness in the inclusive range
 * [0.0, 1.0].
 *
 * @return ESP_OK on success or ESP_ERR_INVALID_ARG for invalid input.
 */
esp_err_t sequence_realtime_set_brightness(uint8_t oscillator_id,
                                           float brightness);

/**
 * @brief Start a linear realtime frequency ramp.
 *
 * The parameter advances once per sequence_tick() from its current value to
 * target_frequency_hz. duration_ms must be a positive multiple of
 * SEQUENCE_TICK_PERIOD_MS.
 *
 * @param[in] oscillator_id Oscillator ID in the range 0 to 4.
 * @param[in] target_frequency_hz Target frequency accepted by oscillator.
 * @param[in] duration_ms Ramp duration in milliseconds.
 *
 * @return ESP_OK on success or ESP_ERR_INVALID_ARG for invalid input.
 */
esp_err_t sequence_realtime_linear_frequency(uint8_t oscillator_id,
                                             float target_frequency_hz,
                                             uint32_t duration_ms);

/**
 * @brief Start a linear realtime brightness ramp.
 *
 * The parameter advances once per sequence_tick() from its current value to
 * target_brightness. duration_ms must be a positive multiple of
 * SEQUENCE_TICK_PERIOD_MS.
 *
 * @param[in] oscillator_id Oscillator ID in the range 0 to 4.
 * @param[in] target_brightness Normalized target brightness in [0.0, 1.0].
 * @param[in] duration_ms Ramp duration in milliseconds.
 *
 * @return ESP_OK on success or ESP_ERR_INVALID_ARG for invalid input.
 */
esp_err_t sequence_realtime_linear_brightness(uint8_t oscillator_id,
                                              float target_brightness,
                                              uint32_t duration_ms);

/**
 * @brief Evaluate all active realtime parameter controls once.
 *
 * Call this function exactly once every SEQUENCE_TICK_PERIOD_MS milliseconds.
 * Each completed linear ramp reaches its target exactly on its final tick and
 * automatically becomes a constant control.
 *
 * @return ESP_OK on success.
 */
esp_err_t sequence_tick(void);

/**
 * @brief Copy the current realtime brightness snapshot.
 *
 * The copy is synchronized so the output callback receives a consistent set of
 * five brightness values. The caller must provide OSCILLATOR_COUNT floats.
 *
 * @param[out] brightnesses Destination array for normalized brightness values.
 *
 * @return ESP_OK on success or ESP_ERR_INVALID_ARG when brightnesses is NULL.
 */
esp_err_t
sequence_get_realtime_brightness(float brightnesses[OSCILLATOR_COUNT]);
